// GENERATED by persona-pipeline — do not edit this copy.
// Source: persona-pipeline/files/scripts/lib/persona.mjs. Edit the source, then run
// `npm run sync:persona-pipeline -- --write` (ADR-0066).
// scripts/lib/persona.mjs — the persona declaration loader (ADR-0066 Decision 2).
//
// The pipeline scripts are persona-neutral: every persona plugin runs the same
// bytes, and each reads who it is from its own plugins/<persona>/persona.json.
// This module finds that file from its own location (import.meta.url), never
// from the working directory or a repository checkout — an installed plugin has
// no repository — so the read stays inside one plugin.
//
// Rules:
//   - Nothing reads the declaration at import time. A module that needs it
//     calls loadPersona() (or an accessor below) when it runs, so a broken
//     declaration cannot break an import: a hook can still exit 0 doing
//     nothing, and a CLI can still say what is wrong.
//   - The format is checked (persona-declaration-1.x), and the declared name
//     must match the plugin the file sits in (.claude-plugin/plugin.json name,
//     else .codex-plugin/plugin.json).
//   - When the declaration is missing, malformed, of an unknown format or for
//     another plugin, loadPersona() throws PersonaDeclarationError. Nothing
//     falls back to another persona's paths: every state-writing command
//     refuses, and every hook does nothing.
//
// The loader checks the declaration's whole structure — the rules of
// persona-pipeline/persona.schema.json, restated here because a plugin carries
// no schema validator — so a schema-invalid declaration refuses writes like a
// missing one. tests/persona-pipeline/test-persona-declaration.mjs holds the
// two in step: every document the schema rejects, the loader rejects. The
// cross-field rules (the decide fallback equals the registry preset, ...) are
// checked at development time by scripts/sync-persona-pipeline.mjs.

import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const PLUGIN_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const FORMAT_RE = /^persona-declaration-1\.(0|[1-9][0-9]*)$/;
const NAME_RE = /^[a-z][a-z0-9-]*$/;
const CAPABILITIES = Object.freeze(['dispatch_target', 'commit_surface', 'legacy_homes', 'profile_presets']);
const ID_RE = /^[a-z][a-z0-9-]*$/;
const NOUN_RE = /^[a-z][a-z '/-]*[a-z]$/;
const SEMVER_RE = /^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$/;
// The format minor this loader reads. A newer minor's unknown scalar is
// forgiven; an unknown object or list is refused at any minor (ADR-0034 §4.1,
// as the schema validator reads it).
const READER_MINOR = 4;
// The document cap the schema validator applies (SCHEMA_MAX_BYTES), measured
// the same way: the declaration pretty-printed, in UTF-8 bytes.
const MAX_BYTES = 64 * 1024;
const TOP_KEYS = ['schema', 'name', 'deliverable_noun', 'runtime_footer_floor', 'capabilities', 'decide', 'verbs', 'peer'];
const DECIDE_KEYS = ['fallback', 'size_presets', 'profile_presets', 'tie_break'];
const VERBS = Object.freeze(['investigate', 'frame', 'decide', 'compose', 'critique', 'refine', 'start']);
const VERB_KEYS = [
  'profiles', 'default_profile', 'request_placeholder', 'ensemble_type', 'artifact',
  'rationale_gate', 'evidence_pointers', 'next_action', 'terminal_requires_convergence',
  'brief_file', 'output_root_env', 'brief_profile', 'brief_ensemble_type',
];
const BRIEF_FILE_RE = /^[a-z][a-z0-9_-]*\.md$/;
const ENV_RE = /^[A-Z][A-Z0-9_]*$/;
const LINE_RE = /^[^\n\r\0]*$/;
const PEER_KEYS = ['privacy_scope', 'privacy_spec', 'images'];
const SPEC_RE = /^[A-Za-z0-9_-][A-Za-z0-9._-]*(\/[A-Za-z0-9_-][A-Za-z0-9._-]*)*$/;

export class PersonaDeclarationError extends Error {
  constructor(message) {
    super(message);
    this.name = 'PersonaDeclarationError';
  }
}

let cached = null;

/** The plugin directory this copy belongs to. */
export function personaPluginRoot() {
  return PLUGIN_ROOT;
}

function manifestName(root) {
  for (const rel of ['.claude-plugin/plugin.json', '.codex-plugin/plugin.json']) {
    let text;
    try {
      text = readFileSync(join(root, rel), 'utf8');
    } catch {
      continue;
    }
    try {
      const name = JSON.parse(text)?.name;
      if (typeof name === 'string' && name.length > 0) return name;
    } catch {
      /* try the other host's manifest */
    }
  }
  return null;
}

function readDeclaration(root) {
  const path = join(root, 'persona.json');
  let text;
  try {
    text = readFileSync(path, 'utf8');
  } catch (err) {
    throw new PersonaDeclarationError(
      `persona declaration ${path} is ${err.code === 'ENOENT' ? 'missing' : `unreadable (${err.code ?? err.message})`}; `
      + 'refusing to act without knowing which persona this plugin is (ADR-0066 Decision 2)',
    );
  }
  let d;
  try {
    d = JSON.parse(text);
  } catch (err) {
    throw new PersonaDeclarationError(`persona declaration ${path} is malformed JSON (${err.message})`);
  }
  if (d === null || typeof d !== 'object' || Array.isArray(d)) {
    throw new PersonaDeclarationError(`persona declaration ${path} is not a JSON object`);
  }
  if (typeof d.schema !== 'string' || !FORMAT_RE.test(d.schema)) {
    throw new PersonaDeclarationError(
      `persona declaration ${path} has an unknown format ${JSON.stringify(d.schema)} (expected persona-declaration-1.x)`,
    );
  }
  if (typeof d.name !== 'string' || !NAME_RE.test(d.name)) {
    throw new PersonaDeclarationError(`persona declaration ${path} has no valid name`);
  }
  const minor = Number(FORMAT_RE.exec(d.schema)[1]);
  const problems = structureProblems(d, minor);
  if (problems.length > 0) {
    throw new PersonaDeclarationError(
      `persona declaration ${path} does not match persona-pipeline/persona.schema.json: ${problems.join('; ')}`,
    );
  }
  const plugin = manifestName(root);
  if (plugin === null) {
    throw new PersonaDeclarationError(
      `persona declaration ${path}: no plugin manifest (.claude-plugin/plugin.json or .codex-plugin/plugin.json) to check its name against`,
    );
  }
  if (plugin !== d.name) {
    throw new PersonaDeclarationError(
      `persona declaration ${path} names persona ${JSON.stringify(d.name)}, but it sits in plugin ${JSON.stringify(plugin)}`,
    );
  }
  return Object.freeze(d);
}

const isObject = (v) => v !== null && typeof v === 'object' && !Array.isArray(v);
const isId = (v) => typeof v === 'string' && v.length <= 64 && ID_RE.test(v);
const isScalar = (v) => v === null || ['string', 'number', 'boolean'].includes(typeof v);
const isLine = (v, { empty = false } = {}) => typeof v === 'string' && v.length <= 512 && LINE_RE.test(v) && (empty || v.length > 0);

/**
 * The schema's structure, as a list of what is wrong (empty when valid). At
 * every depth, a key the format does not know is refused, except a scalar in a
 * declaration of a newer minor than this loader reads: that one is ignored, as
 * the schema validator ignores it (forward compatibility).
 */
function structureProblems(d, minor) {
  const problems = [];
  const no = (what) => problems.push(what);
  const newer = minor > READER_MINOR;
  // The keys of `obj` outside `known`, less the ones a newer minor may add.
  const unknown = (obj, known) => Object.keys(obj).filter((k) => !known.includes(k) && !(newer && isScalar(obj[k])));
  if (Buffer.byteLength(`${JSON.stringify(d, null, 2)}\n`, 'utf8') > MAX_BYTES) no(`larger than ${MAX_BYTES} bytes`);
  for (const key of unknown(d, TOP_KEYS)) no(`unknown key ${key}`);
  if (d.name.length > 32) no('name longer than 32 characters');
  if (d.deliverable_noun !== undefined && !(typeof d.deliverable_noun === 'string' && d.deliverable_noun.length <= 64 && NOUN_RE.test(d.deliverable_noun))) no('invalid deliverable_noun');
  if (d.runtime_footer_floor !== undefined && !(typeof d.runtime_footer_floor === 'string' && SEMVER_RE.test(d.runtime_footer_floor))) no('invalid runtime_footer_floor');
  const caps = d.capabilities;
  if (!isObject(caps) || CAPABILITIES.some((c) => typeof caps[c] !== 'boolean') || unknown(caps, CAPABILITIES).length > 0) {
    no(`capabilities must set exactly ${CAPABILITIES.join(', ')} to true or false`);
  }
  if (d.verbs !== undefined) verbProblems(d.verbs, unknown, no);
  if (d.peer !== undefined) peerProblems(d.peer, unknown, no);
  const decide = d.decide;
  if (!isObject(decide)) {
    no('decide is missing');
    return problems;
  }
  for (const key of unknown(decide, DECIDE_KEYS)) no(`unknown key decide.${key}`);
  const fb = decide.fallback;
  if (!isObject(fb) || unknown(fb, ['preset_id', 'axes']).length > 0 || !isId(fb.preset_id)
    || !Array.isArray(fb.axes) || fb.axes.length < 2 || fb.axes.length > 16) {
    no('decide.fallback must be { preset_id, axes[2..16] }');
  } else {
    fb.axes.forEach((a, i) => {
      const ok = isObject(a)
        && unknown(a, ['id', 'labels', 'question', 'role', 'gate']).length === 0
        && isId(a.id)
        && isObject(a.labels) && unknown(a.labels, ['en', 'ko']).length === 0
        && typeof a.labels.en === 'string' && a.labels.en.length <= 128
        && (a.labels.ko === null || (typeof a.labels.ko === 'string' && a.labels.ko.length <= 128))
        && typeof a.question === 'string' && a.question.length <= 2048
        && (a.role === 'decisive' || a.role === 'supporting')
        && typeof a.gate === 'boolean';
      if (!ok) no(`decide.fallback.axes[${i}] must be { id, labels {en, ko}, question, role, gate }`);
    });
  }
  const sizes = decide.size_presets;
  const SIZES = ['minor', 'standard', 'major'];
  if (!isObject(sizes) || SIZES.some((k) => !isId(sizes[k])) || unknown(sizes, SIZES).length > 0) {
    no('decide.size_presets must map minor, standard and major to preset ids');
  }
  const pp = decide.profile_presets;
  if (pp !== undefined
    && !(isObject(pp) && Object.entries(pp).every(([k, v]) => (ID_RE.test(k) ? isId(v) : newer && isScalar(v))))) {
    no('decide.profile_presets must map profile ids to preset ids');
  }
  if (decide.tie_break !== undefined
    && !(Array.isArray(decide.tie_break) && decide.tie_break.length >= 1 && decide.tie_break.length <= 16 && decide.tie_break.every(isId))) {
    no('decide.tie_break must be a list of 1..16 axis ids');
  }
  return problems;
}

/** Format 1.1: `verbs`, the per-verb fields (structure only; the generator checks the rest). */
function verbProblems(verbs, unknown, no) {
  if (!isObject(verbs)) {
    no('verbs must be an object keyed by verb');
    return;
  }
  for (const key of unknown(verbs, VERBS)) no(`unknown key verbs.${key}`);
  for (const verb of VERBS) {
    if (!Object.hasOwn(verbs, verb)) continue;
    const v = verbs[verb];
    const at = `verbs.${verb}`;
    if (!isObject(v)) {
      no(`${at} must be an object`);
      continue;
    }
    for (const key of unknown(v, VERB_KEYS)) no(`unknown key ${at}.${key}`);
    if (v.profiles !== undefined
      && !(Array.isArray(v.profiles) && v.profiles.length >= 1 && v.profiles.length <= 16 && v.profiles.every(isId))) {
      no(`${at}.profiles must be a list of 1..16 profile ids`);
    }
    // Format 1.4: investigate's brief profile and brief ensemble type, ids too.
    for (const key of ['default_profile', 'ensemble_type', 'brief_profile', 'brief_ensemble_type']) {
      if (v[key] !== undefined && !isId(v[key])) no(`${at}.${key} must be an id`);
    }
    for (const key of ['request_placeholder', 'rationale_gate', 'evidence_pointers', 'next_action']) {
      if (v[key] !== undefined && !isLine(v[key])) no(`${at}.${key} must be one non-empty line of at most 512 characters`);
    }
    if (v.artifact !== undefined
      && !(Array.isArray(v.artifact) && v.artifact.length >= 1 && v.artifact.length <= 40 && v.artifact.every((l) => isLine(l, { empty: true })))) {
      no(`${at}.artifact must be a list of 1..40 lines`);
    }
    if (v.terminal_requires_convergence !== undefined && typeof v.terminal_requires_convergence !== 'boolean') {
      no(`${at}.terminal_requires_convergence must be true or false`);
    }
    // Format 1.3: investigate's brief names, where not derived.
    if (v.brief_file !== undefined && !(typeof v.brief_file === 'string' && v.brief_file.length <= 64 && BRIEF_FILE_RE.test(v.brief_file))) {
      no(`${at}.brief_file must be a lower-case *.md file name`);
    }
    if (v.output_root_env !== undefined && !(typeof v.output_root_env === 'string' && v.output_root_env.length <= 64 && ENV_RE.test(v.output_root_env))) {
      no(`${at}.output_root_env must be an upper-case variable name`);
    }
  }
}

/** Format 1.2: `peer`, the peer policy. */
function peerProblems(peer, unknown, no) {
  if (!isObject(peer)) {
    no('peer must be an object');
    return;
  }
  for (const key of unknown(peer, PEER_KEYS)) no(`unknown key peer.${key}`);
  if (!isLine(peer.privacy_scope)) no('peer.privacy_scope must be one non-empty line of at most 512 characters');
  if (!(typeof peer.privacy_spec === 'string' && peer.privacy_spec.length <= 256 && SPEC_RE.test(peer.privacy_spec))) {
    no('peer.privacy_spec must be a plugin-relative path');
  }
  if (typeof peer.images !== 'boolean') no('peer.images must be true or false');
}

function field(d, path) {
  let cur = d;
  for (const part of path.split('.')) {
    if (cur === null || typeof cur !== 'object' || !Object.hasOwn(cur, part)) return undefined;
    cur = cur[part];
  }
  return cur;
}

/**
 * The validated declaration. `require` names the fields the caller reads
 * (dotted paths); a missing one throws.
 */
export function loadPersona({ require = [] } = {}) {
  if (cached === null) cached = readDeclaration(PLUGIN_ROOT);
  for (const path of require) {
    if (field(cached, path) === undefined) {
      throw new PersonaDeclarationError(
        `persona declaration ${join(PLUGIN_ROOT, 'persona.json')} lacks ${path}, which this script reads`,
      );
    }
  }
  return cached;
}

/** The persona name. */
export function personaName() {
  return loadPersona().name;
}

/** Whether the persona declares a capability on (ADR-0066 Decision 3). */
export function capabilityOn(capability) {
  if (!CAPABILITIES.includes(capability)) throw new PersonaDeclarationError(`unknown capability ${capability}`);
  return loadPersona().capabilities[capability] === true;
}

// ---- derived identity (V1) ----------------------------------------------------

/** `.agentic-plugins/state/<name>` — the persona's state home, repo-relative. */
export function stateDirRel() {
  return `.agentic-plugins/state/${personaName()}`;
}

/** `/<name>:` — the command prefix. */
export function commandPrefix() {
  return `/${personaName()}:`;
}

/** `<name>-active-metadata` — the SessionStart re-injection marker. */
export function metadataTag() {
  return `${personaName()}-active-metadata`;
}

/** `AGENTIC_<NAME>_PROFILE` — the L4 profile variable, read only with profile_presets on. */
export function profileEnvVar() {
  return `AGENTIC_${personaName().toUpperCase().replace(/-/g, '_')}_PROFILE`;
}

/**
 * For a CLI entry: load the declaration, or print why it cannot be loaded and
 * return false, so the caller exits non-zero before touching any state.
 */
export function personaOrRefuse(scriptName, stderr = process.stderr) {
  try {
    loadPersona();
    return true;
  } catch (err) {
    if (!(err instanceof PersonaDeclarationError)) throw err;
    stderr.write(`✗ ${scriptName}: ${err.message}\n`);
    return false;
  }
}
